config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'
  get 'posts/index'
  get "/" => "home#top"
  get "/about" => "home#about"
  get "typings/edit" => "typings#edit"
  get "/typings" => "typings#index"
  get "/typings/result" => "typings#result"
  get "/categories/index" => "categories#index"

    resources :posts
    resources :categories 
    resources :characters ,only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true 
  
  has_many :posts
end

app/models/character.rb
class Character < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :word, presence: true
  validates :mean, presence: true 

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_character

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_character
    @character = Character.find_by(id: 1)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def show
    @character = Character.new(id: 1, name: "keybo", experience: 0)
    @character = Character.find_by(id: 1)
  end
  # def index
    
  # end
  # def create
  #   @character = Character.new(character_params)
  #   if @character.save
  #     redirect_to "/"
  #   end
  # end

  # private

  # def character_params
  #   params.require(:character).permit(:name, :level, :experience)
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_character

  def index
    @posts = if params[:category_id].present?
                  Post.where(category_id: params[:category_id]).order(created_at: sort_direction)
              else
                  Post.order(created_at: sort_direction)
              end
    @categories = Category.all
  end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      @categories = Category.all

      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def edit
    @categories = Category.all
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      @categories = Category.all

      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:word, :mean, :category_id)
  end

  def sort_column
    %w[word mean].include?(params[:sort_column]) ? params[:sort_column] : "word"
  end

  def sort_direction
    %w[asc desc].include?(params[:sort_order]) ? params[:sort_order] : "asc"
  end

  def set_character
    @character = Character.find_by(id: 1)
  end
end

app/controllers/typings_controller.rb
class TypingsController < ApplicationController
  def index
    @character = Character.new(id: 1, name: "keybo", experience: 0)
    @character = Character.find_by(id: 1)
  end

  def edit
    @dictionaries = Post.all
    @character = Character.find_by(id: 1)
    # @random_posts = Post.order("RAND()").limit(10) #ローカル
    @random_posts = Post.order("RANDOM()").limit(10)

  end

  def result
    @character = Character.find_by(id: 1)
    @success = params[:success].to_i
    @character.update(experience: @character.experience + @success)
    if @character.experience >= 20
      @character.update(level: @character.level+5, experience: @character.experience - 20)
    end
    @result = {
      success: params[:success],
      failed: params[:failed],
      character_level: @character.level,
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/typings_helper.rb
module TypingsHelper
end

app/views/categories/edit.html.erb
<%= render "shared/header" %>
<body style="background-color: #BFE6FC">
  <div class="category-new-main">
    <div class="form__wrapper">
      <h3 class="page-heading">辞書を編集する</h3>
      <%= form_with(model: @category, local: true) do |f| %>
        <div class="field" style="text-align: center;">
          <%= f.label :name, "辞書の種類" %><br>
          <%= f.text_area :name, class: "form__text", id: "dictionary_word" %>
        </div>
        <div class="content_save_btn">
          <button class="button-6" role="button"><span>保存する</span></button>
        </div>
      <% end %>
      <div class="content_return_btn">
        <a href="/posts/index" class="button-6"><span>辞書に戻る</span></a>
      </div>
    </div>
  </div>

</body>

app/views/categories/index.html.erb
<body style="background-color: #BFE6FC">
  <%= render "shared/header" %>
<div class="contents">
  <div class="content_new_btn">
    <a href="/categories/new" class="button-6 button-new"><span>新しい辞書を登録する</span></a>
  </div>
  <div class="category-card-wrapper">
    <div class="category-card-container">
      <% @categories.each do |category| %>
      <div class="category-card">
        <div class="category-name"><%= category.name%></div>
        <div class="category-card__buttons">
          <%= link_to image_tag("edit-btn.png", size: "25x20"), edit_category_path(category), class: "before-btn-edit"%>
          <%= link_to image_tag("delete-btn.png", size: "18x18"), category_path(category), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn-delete"%>
        </div>
      </div>
      <% end %>
    </div>
    <div class="content_return_btn">
      <a href="/posts/index" class="button-6"><span>戻る</span></a>
    </div>
  </div>
</div>
</body>

app/views/categories/new.html.erb
<%= render "shared/header" %>
<body style="background-color: #BFE6FC">
  <div class="category-new-main">
    <div class="form__wrapper">
      <h3 class="page-heading">新しい辞書を登録する</h3>
      <%= form_with(model: @category, local: true) do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
        <div class="field" style="text-align: center;">
          <%= f.label :name, "辞書の種類" %><br>
          <%= f.text_area :name, class: "form__text", id: "dictionary_word" %>
        </div>
        <div class="new-content__btn">
          <div class="content_save_btn">
            <button class="button-6" role="button"><span>保存する</span></button>
          </div>
          <% end %>
          <div class="content_return_btn">
          <a href="/posts/index" class="button-6"><span>辞書に戻る</span></a>
        </div>
      </div>
    </div>
  </div>

</body>

app/views/categories/show.html.erb
<body style="background-color: #BFE6FC">
<%= render "shared/header" %>
<h1><%= @category.name %></h1>
</body>

app/views/characters/index.html.erb
<%= form_with model:Character.new do |form| %>
  <%= form.text_field :name, value: 'keybo' %>
  <%= form.number_field :level, value: 0 %>
  <%= form.number_field :experience, value: 0 %>
  <%= form.submit 'Create Character' %>
<% end %>

app/views/characters/show.html.erb
<div class="body">
  <div class ="head">
  </div>
  <div class="show-character-wrap">
    <div class="show-my-characters">
      <div class ="show-character_status">
        <div class="balloon-think">
          <div class="name dot-font">Yours <%= @character.name %></div>
          <div class="level dot-font"> Level   <%= @character.level %></div>
        </div> 
      </div>
      <div class="my__character"><%= image_tag("k-#{@character.level}.gif")%></div>
    </div>
  </div>
</div>
  <%= render "shared/footer" %>

app/views/home/about.html.erb
<div class="about-body">
<div class="about-contents">
  <div class="title">
  </div>
  <div class="about">
    <div class="box" id="js-target">
      こんにちは
      ボクの名前はkeyboです。<br/>
      
      このアプリは自分で辞書を作成できます。<br/>
      そして<br/>
      その辞書に登録した単語でタイピング練習ができます。<br/>
      正解数によってボクは成長します。<br/>
      これから一緒に成長していきましょう。<br/>
    </div>
    <div class="keybo">  <%= image_tag("k-first.gif") %> </div>
  </div>
</div>
  <%= render "shared/footer" %>
</div>

app/views/home/top.html.erb
<body>
<div class="main top-main">
  <div class="top-message">
    <span class="dot-font" id="ityped"></span>
      <script>
      ityped.init(document.querySelector("#ityped"), {
        strings: ['MINE TYPING', 'and Enjoy!'],
            typeSpeed:  200//タイピングのスピード
      })
      </script> 
  </div>
  <nav class="main__nav">
    <div class="main__nav__items">
    <%= link_to about_path, class: "dot-font" do %>
      <%= image_tag("mark_shoshinsha.png", size: "50x50", style: "vertical-align: middle; margin-right: 10px;") %>
      About
    <% end %>
    <%= link_to posts_path, class: "dot-font" do %>
      <%= image_tag("book_blue.png", size: "50x50", style: "vertical-align: middle; margin-right: 10px;") %>
      Dictionary
    <% end %>
    <%= link_to typings_path, class: "dot-font" do %>
      <%= image_tag("t.png", size: "50x50", style: "vertical-align: middle; margin-right: 10px;") %>
      Typing
    <% end %>
    <%= link_to character_path(1), class: "dot-font" do %>
      <%= image_tag("egg.png", size: "50x50", style: "vertical-align: middle; margin-right: 10px;") %>
      Character
    <% end %>
    </div>
  </nav>
</div>
<footer>
  &copy; chsato harada 2023
</footer>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/css/index.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DotGothic16&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/index.js"></script>
    <script src="https://unpkg.com/ityped@1.0.3"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <%= yield %>

</html> 

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
<%= render 'shared/error_messages', model: f.object %>
<div class="field" style="text-align: center;">
  <%= f.collection_select :category_id, @categories || [], :id, :name, { prompt: '辞書を選択' }, { class: 'form-control' } %>
</div>
<div class="field" style="text-align: center;">
  <%= f.label :word, "単語・用語" %><br>
  <%= f.text_area :word, class: "form__text", id: "dictionary_word" %>
</div>
<div class="field" style="text-align: center;">
  <%= f.label :mean, "意味" %><br>
  <%= f.text_area :mean, class: "form__text", id: "dictionary_mean" %>
</div>
  <div class="content_save_btn">
    <button class="button-6" role="button"><span>保存する</span></button>
  </div>
<% end %>
<div class="content_return_btn">
  <a href="/posts/index" class="button-6"><span>辞書に戻る</span></a>
</div>

app/views/posts/_word.html.erb
<%= select_tag(:sort_order, options_for_select([['昇順', 'asc'], ['降順', 'desc']], params[:sort_order]), class: 'form-control') %>
<div class="button-section">
  <a href="/posts/new" class="btn03 pushdown"><span>単語・用語を登録する</span></a>
  <a href="/categories/index" class="btn03 pushdown"><span>辞書一覧</span></a>
</div>
<div class="contents">
  <div class="card-wrapper">
    <div class="card-container">
      <% @posts.each do |post| %>
        <div class="card">
          <div class="card__words"><%= post.word %></div>
          <div class="card__means">
            <div class="card__mean"><%= post.mean %></div>
            </div>
          <div class="card__buttons">
            <%= link_to image_tag("edit-btn.png", size: "25x20"), edit_post_path(post), class: "before-btn-edit"%>
            <%= link_to image_tag("delete-btn.png", size: "18x18"), post_path(post), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn-delete"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</body>

app/views/posts/edit.html.erb
<%= render "shared/header" %>
<body style="background-color: #ABF3E6">
  <div class="post-main">
    <div class="form__wrapper">
      <div class="form-content__top">単語・用語を編集する</div>
        <%= render partial: "form" %>
    </div>
  </div>
</body>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<body style="background-color: #ABF3E6">

  <div class="button-section">
    <div class="class-select-tab">
    <%= select_tag(:sort_order, options_for_select([['昇順', 'asc'], ['降順', 'desc']], params[:sort_order]), class: 'form-control') %>
    <%= select_tag(:category_id, options_from_collection_for_select(@categories, "id", "name"), prompt: '辞書を絞り込む', class: 'form-control') %> 
    </div>
    <div class="add-btns">
      <a href="/categories/new" class="button-6 button-new"><span>新しい辞書を登録する</span></a>
      <a href="/posts/new" class="button-6 button-large"><span>単語を登録する</span></a>
      <a href="/categories/index" class="button-6"><span>辞書一覧</span></a>
    </div>
  </div>

  <div class="card-wrapper contents">
    <div class="card-container">
      <% @posts.each do |post| %>
        <div class="card">
          <div class="card__words"><%= post.word %></div>
            <div class="card__mean"><%= post.mean %></div>
          <div class="card__buttons">
            <%= link_to image_tag("edit-btn.png", size: "25x20"), edit_post_path(post), class: "before-btn-edit"%>
            <%= link_to image_tag("delete-btn.png", size: "18x18"), post_path(post), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn-delete"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</body>
<%= javascript_pack_tag 'dictionary_order' %>

app/views/posts/new.html.erb
<%= render "shared/header" %>
<body style="background-color: #ABF3E6">

  <div class="post-main">
    <div class="form__wrapper">
      <div class="form-contents">
        <h3 class="page-heading">単語・用語を登録する</h3>
      <%= render partial: "form" %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  &copy; chsato harada 2023
</footer>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header_logo">
    <div class="header__title__img">
      <%= link_to "/", class: "my-class" do %>
      <%= image_tag("k-#{@character.level}.gif", width: 70, height: 70) %>
      <% end %>
    </div>
    <div class="header__title__logo">
      <%= link_to "MINE TYPING", "/", class: "dot-font", style: "font-size: 50px;" %>
    </div>
  </div>
  <div class="menu-icon">
    <i class="fa-solid fa-bars"></i>
  </div>
</div>
<div class="h-container">
  <nav class="hamburger__nav" style="position: absolute; z-index: 1; display: none">
    <div class="main__nav__items">
      <% nav_items = [
        { link_path: about_path, img_src: "question.png", label: "About" },
        { link_path: typings_path, img_src: "t.png", label: "Typing" },
        { link_path: posts_path, img_src: "book_blue.png", label: "Dictionary" },
        { link_path: "#", img_src: "egg.png", label: "Characters" }
      ] %>
      <% nav_items.each do |nav_item| %>
        <%= link_to nav_item[:link_path], class: "dot-font" do %>
          <%= image_tag(nav_item[:img_src], width: 60, height: 60, style: "vertical-align: middle;") %>
          <span style="font-size: 50px; display: inline-block; vertical-align: middle;"><%= nav_item[:label] %></span>
        <% end %>
      <% end %>
    </div>
  </nav>
</div>
</div>
  </div>
  </nav>
</div>

app/views/typings/edit.html.erb
<div class="body">

  <div id="t-container">
    <div class="q-wrap">
      <div class="word-section">
        <div id="word"></div>
        <input type="text" id="input" oninput="checkInput()" autofocus>
      </div>
      <div class="q-wrap">
        <div id="mean"></div>
      </div>
      <div class="keyboard-section">
        <input class="input" placeholder="Tap on the virtual keyboard to start" />
        <div class="simple-keyboard"></div>
      </div>
            <div class="character-wrap">
        <div class="character__judge">
          <%= image_tag("mark_maru.png", alt: "Success Image", class: "success-image hidden") %>
          <%= image_tag("mark_batsu.png", alt: "Failed Image", class: "failed-image hidden") %>
        </div>
        <div class="character">
          <%= image_tag("k-#{@character.level}.gif", alt: "Character Image") %>
        </div>
      </div>
      <div class="exit-wrap">
        <%= link_to "EXIT", "/", class: "exit dot-font" %>
      </div>
    </div>
</div>
</div>
<%= render "shared/footer" %>
<%= javascript_pack_tag 'keyboard' %>

<script>
  var dictionaries = <%= raw @random_posts&.to_json || [].to_json %>;
  let currentWordIndex = 0;
  const input = document.getElementById("input");
  const meanDom = document.getElementById("mean");
  let currentFieldValue = input.value;
  let successCount = 0;
  let failedCount = 0;
  const characterImage = document.querySelector(".character img:first-child");
  const successImage = document.querySelector(".success-image");
  const failedImage = document.querySelector(".failed-image");

  function displayWordAndMean(dictionary, index=0) {
    if (!dictionary) return null;

    word.innerHTML = dictionary.word;
    input.placeholder = dictionary.word;
    meanDom.innerHTML = dictionary.mean;
  }

function checkInput() {
  currentFieldValue = currentFieldValue += input.value;

  if (!dictionaries[currentWordIndex] || (input.value.length != dictionaries[currentWordIndex].word.length)) return;

  if (input.value == dictionaries[currentWordIndex].word) {
    successCount++;
    currentWordIndex++;
    input.value = "";
    successImage.classList.remove("hidden");
    failedImage.classList.add("hidden");
  } else {
    failedCount++;
    currentWordIndex++;
    input.value = "";
    failedImage.classList.remove("hidden");
    successImage.classList.add("hidden");
    displayWordAndMean(dictionaries[currentWordIndex]);
  }

  if (dictionaries[currentWordIndex]) {
    // 成功した時に次があれば表示
    displayWordAndMean(dictionaries[currentWordIndex]);
  } else {
    // なければresultにリダイレクト
    window.location.href = `/typings/result?success=${successCount}&failed=${failedCount}`;
  }
}

  displayWordAndMean(dictionaries[currentWordIndex]);
</script>

<style>
  .hidden {
    display: none;
  }
</style>

app/views/typings/index.html.erb
<div class="body">
<div class ="head">
</div>
  <div class="typing-wrap">
    <div class="start-wrap">
      <%= link_to "START", typings_edit_path, class: "start dot-font" %>
    </div>
    <p class="dot-font bound ">
    <span>H</span>
    <span>e</span>
    <span>l</span>
    <span>l</span>
    <span>o</span>
    <span>!</span>
    </p>
      <div class="my-characters">
        <div class="character"><%= image_tag("k-#{@character.level}.gif")%></div>
        <div class ="character_status">
          <div class="name dot-font"><%= @character.name %></div>
          <div class="character_icon"><%= image_tag("flower.png")%></div>
          <div class="level dot-font"> Level   <%= @character.level %></div>
        </div>
      </div>
    </div>
</div>
  <%= render "shared/footer" %>

app/views/typings/result.html.erb
<div class="body">
<div class ="head">
</div>
  <div class="result-wrap">
    <div class="result-comment">
      <span>１０問中</span>  <%= @result[:success] %>問正解しました！
    </div>
    <div class="my-characters">
      <div class="character"><%= image_tag("k-#{@character.level}.gif")%></div>
      <div class ="character_status">
        <div class="name dot-font"><%= @character.name %></div>
        <div class="character_icon"><%= image_tag("flower.png")%></div>
        <div class="level dot-font"><%= @character.level %> Level</div>
    </div>
    <div class="r-link">
      <%= link_to "続ける", "/typings", class: "btn02 btnarrow2", style: "font-size: 15px "%>
      <%= link_to "辞書に戻る", posts_index_path, class: "btn02 btnarrow2", style: "font-size: 15px "%>
    </div>
  </div>
</div>